### ISSUE TITLE
Tooltip on focus

### ISSUE THREAD

**Issue by nico3333fr** [m4dz/aria-tips#6]
Hi,

you might add focus management following design pattern : http://www.w3.org/TR/wai-aria-practices/#tooltip

> Note: If the tooltip is invoked when the trigger element gets focus, then it should be dismissed 
> when it no longer has focus (onBlur). If the tooltip is invoked with mouseIn, then it should 
> be dismissed with a mouseOut. 

Nice work anyway ;)
Nicolas

**Comment by m4dz** [comment]
As suggested [here](https://twitter.com/johan_ramon/status/589004289743388672) and [here](https://twitter.com/johan_ramon/status/589005578254606336), adding a feature to mask the tip with ESC event it it has focus (with blur, anyway) may be more comfortable for user that want to mask the tip without loosing the focus.
